-keep class com.danil.kleshchin.tvseries.data.detailed.entity.* { *; }
-keep class com.danil.kleshchin.tvseries.data.popular.datasource.network.entity.* { *; }
-keep class com.danil.kleshchin.tvseries.data.popular.datasource.local.entity.* { *; }
